### ISSUE TITLE
Refactor Gamestate (Optimized for client serialization)

### ISSUE THREAD

**Issue by jhparkt** [ucsd-cse125-sp24/group3#35]
Currently object class contains data, which are not necessary for the clients.

Create mapping of object ID with other data and keep in within the server, so that it does not have to be sent to client.

**Comment by gilkeidar** [comment]
Some new modifications to the refactored game state (`ServerGameState` + `SharedGameState`):

1. All objects (base + derived classes) in `ServerGameState` have a `generateSharedObject()` virtual method that converts them into a `SharedObject` (`SharedGameState` has a single `vector<SharedObject> objects` vector of all objects in the game instance)
    1. `SharedObject` contains `std::optional` fields for optional structs + need good documentation so when writing client-side code the developer is aware of which fields will be filled for different `SharedObject`s based on the `ObjectType type` field.
2. `ServerGameState` type-specific vectors should contain object pointers (maybe worse cache performance but we don't need to worry about vector reallocation, we can keep the object typeID, and we can have more generic vectors (e.g., `vector<Item *>` as opposed to `vector<Weapons>` and `vector<Armors>` as well as more specific derived classes like `vector<SwordOfHercules>` or whatever which may not have many instances in the game).

**Comment by gilkeidar** [comment]
3. Refactor `ServerGameState` object handling into a single `ObjectManager` class.

The `ObjectManager` class maintains all `Object` (and derived class) `SmartVector`s and provides APIs for accessing these (`createObject(ObjectType type)`, etc.)

Also offers a `generateSharedObjects()` method that generates the `SmartVector<SharedObject> objects` vector used by the `SharedGameState` class.
