### ISSUE TITLE
Game start animation

### ISSUE THREAD

**Issue by atar13** [ucsd-cse125-sp24/group3#46]
Have an animation that plays as you enter the game stage. This could be the movement of the camera as it enters the entrance to the maze.

**Comment by gilkeidar** [comment]
Game main menu could be designed as the UI play / options / quit buttons over a rendering of the entrance to the maze (a dark passageway entering the darkness) and surrounded by two torches attached to the walls (maybe the UI options can be in the middle, where the passageway is).

Then when the player clicks "play" an animation can play where the camera moves into the dark passageway and then the game starts.
